[build]
  publish = "."
  command = "node build-config.js"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_PATHS = "firebase-config.js,NETLIFY_ENV_VARS.md"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"

# As variáveis de ambiente serão configuradas na interface do Netlify
# NÃO coloque credenciais aqui!
